[package]
name = "storyrender"
version = "0.1.0"
authors = ["Andrew Wheeler <genusis@spirean.com>"]
edition = "2018"

[dependencies]
nom = "5.1.1"
tinyexpr = { git = "https://git.codentium.com/Genusis/tinyexpr-rs" }
regex = "1"