[package]
name = "storyrender"
version = "0.1.0"
authors = ["Andrew Wheeler <genusis@spirean.com>"]
edition = "2018"

[dependencies]
nom = "6.2.1"
tinyexpr = { git = "https://github.com/genusistimelord/tinyexpr-rs" }
regex = "1"
float-cmp = "0.8"